name: Infinite Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm install
        # Opcional: Si necesitas instalar los navegadores de Playwright
        # npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    # Opcional: Si deseas subir un informe o reporte después de las pruebas
    # - uses: actions/upload-artifact@v4
    #    if: always()
    #    with:
    #      name: playwright-report
    #      path: playwright-report/
    #      retention-days: 30
