on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright install

      - name: Run Infinite tests
        run: npm run test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{ matrix.os }}
          path: |
            ./assets
            ./features
            ./test-result
            ./test-results
            index.html

  jmeter-load-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Descargar JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz | tar xz
          export PATH=$PATH:$PWD/apache-jmeter-5.4.1/bin

      - name: Ejecutar pruebas JMeter
        run: |
           jmeter -n -t jmeter/Login.jmx -l resultados.jtl

      - name: Subir archivos de resultados
        uses: actions/upload-artifact@v2
        with:
          name: resultados-jmeter
          path: resultados.jtl
