on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright install

      - name: Run Infinite tests
        run: npm run test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always() # Subir el reporte siempre, incluso si hay errores en la ejecución de las pruebas
        with:
          name: test-report-${{ matrix.os }} # Cambio en el nombre del artefacto
          path: |
            ./assets
            ./features
            ./test-result
            ./test-results
            index.html

  jmeter-load-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download and Install JMeter
        run: |
          Invoke-WebRequest -Uri "https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.1.zip" -OutFile "apache-jmeter.zip"
          Expand-Archive -Path apache-jmeter.zip -DestinationPath C:\jmeter
          $env:PATH += ";C:\jmeter\apache-jmeter-5.4.1\bin"

      - name: Ejecutar pruebas JMeter
        run: |
          jmeter -n -t jmeter/Login.jmx -l resultados.jtl

      - name: Subir archivos de resultados
        uses: actions/upload-artifact@v2
        with:
          name: resultados-jmeter
          path: resultados.jtl
