name: Infinite Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm install
        # Opcional: Si necesitas instalar los navegadores de Playwright
        # npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright install
    - name: Run Infinite tests
      run: npm run test
    - name: Send email with test report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.Thiago Turk }}
        password: ${{ secrets.messi2024A }}
        subject: Test Report
        body: |
          Attached is the test report.
        to: thiagotobiias23@gmail.com
        from: turkthiago3@gmail.com
        attachments: ./index.html
