name: Kubernetes Job

on:
  push:
    branches:
      - moria

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: lachlanevenson/k8s-kubectl:latest
      options: --privileged  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
         curl.exe -LO "https://dl.k8s.io/release/v1.30.0/bin/windows/amd64/kubectl.exe"
         curl.exe -LO "https://dl.k8s.io/v1.30.0/bin/windows/amd64/kubectl.exe.sha256"
         CertUtil -hashfile kubectl.exe SHA256
         type kubectl.exe.sha256
          $(Get-FileHash -Algorithm SHA256 .\kubectl.exe).Hash -eq $(Get-Content .\kubectl.exe.sha256)
          kubectl version --client
          kubectl version --client --output=yaml

      - name: Check Kubernetes Cluster
        if: github.ref == 'refs/heads/moria' 
        run: |
          kubectl get pods -A | grep -v -E 'Running|Completed|Terminating'
          kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }'
          # kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }' | sort -nr -k 6 | grep -E '75|80|90|100' | grep -E 'artemis|export|bob|roshi|flexo'

      - name: Extract Pods
        if: github.ref == 'refs/heads/moria' 
        run: |
          kubectl get pods -A > pods.txt
          cat pods.txt
