name: Kubernetes Job

on:
  push:
    branches:
      - moria

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: lachlanevenson/k8s-kubectl:latest
      options: --privileged  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl  # Instalar kubectl en el contenedor
          echo "$KUBE_CONFIG" > $HOME/.kube/config  # Configurar el archivo de configuración de kubectl
          kubectl version --client  # Verificar la versión de kubectl

      - name: Check Kubernetes Cluster
        if: github.ref == 'refs/heads/moria' 
        run: |
          kubectl get pods -A | grep -v -E 'Running|Completed|Terminating'
          kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }'
          kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }' | sort -nr -k 6 | grep -E '75|80|90|100' | grep -E 'artemis|export|bob|roshi|flexo'
