name: Kubernetes Job

on:
  push:
    branches:
      - moria

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: lachlanevenson/k8s-kubectl:latest
      options: --privileged  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
         mkdir -p ~/.kube  
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"  # Descargar kubectl
         chmod +x ./kubectl  
         mv ./kubectl /usr/local/bin/kubectl  # Mover kubectl al directorio de comandos
         kubectl version --client  
      - name: Check Kubernetes Cluster
        if: github.ref == 'refs/heads/moria' 
        run: |
          # kubectl get pods -A | grep -v -E 'Running|Completed|Terminating'
          kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }'
          # kubectl get hpa -n prod-cl | grep -v keda | awk '{ print $1, "\t", $2, "\t", $3, "\t", $4, "\t", $5, "\t", $6, "\t", $7 }' | sort -nr -k 6 | grep -E '75|80|90|100' | grep -E 'artemis|export|bob|roshi|flexo'
