name: Automated Testing

on:
  push:
    branches:
      - playwright
  pull_request:
    branches:
      - playwright

jobs:
  login:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        account-index: [0, 1, 2, 3, 4]

    env:
      USERNAME_0: alejandro.gamboa@lirmi.com
      PASSWORD_0: secret
      USERNAME_1: alex.silva@lirmi.com
      PASSWORD_1: secret
      # Define más variables de entorno para cada cuenta adicional si es necesario

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install

      - name: Cache Playwright dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.js') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright
        run: npx playwright install

      - name: Run Infinite tests
        run: npm run test

      # Resto de tus pasos de configuración...

      - name: Run tests with different accounts
        run: |
          npm test 
