name: Automated Testing

on:
  push:
    branches:
      - playwright
  pull_request:
    branches:
      - playwright

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Install Playwright
      - name: Install Playwright
        run: npx playwright install

      # Run tests
      - name: Run tests
        run: npm test
