
      name: Automated Testing

      on:
        push:
          branches:
            - playwright
        pull_request:
          branches:
            - playwright
      
      
      jobs:
        Login:
          runs-on: ubuntu-latest
      
          strategy:
            matrix:
              account-index: [0, 1, 2, 3, 4]
      
          steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
      
            - name: Install dependencies
              run: npm install
      
            - name: Install Playwright
              run: npx playwright install       
      
            - name: Run tests
              run: |
                npm test -- --accountIndex ${{ matrix.account-index }}
      