name: Test 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Display the commit message and updated files
        run: |
          echo "Commit message:"
          git log -1 --pretty=format:"%s"
          echo ""
          echo "Updated files:"
          git diff-tree --no-commit-id --name-only -r $(git log -1 --format="%H")
        
 
