name: Automated Testing

on:
  push:
    branches:
      - playwright
  pull_request:
    branches:
      - playwright
      
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install Node.js and dependencies
      - name: Install Node.js and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Cache Playwright dependencies
      - name: Cache Playwright dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.js') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Install Playwright
      - name: Install Playwright
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx playwright install

  test_login_1:
    runs-on: ubuntu-latest
    
    needs: setup
    
    steps:
      - name: Run Login1.feature tests
        run: npm test Login1.feature
